config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resource :transaction, only: [:create]
  resource :session
  resource :registration
  resource :password_reset
  resource :password
  resources :merchants, only: [:index, :show]
  resources :tasks, only: [:index] do
      collection do
          post :sync_ynab_transactions
          post :sync_ynab_payees
          post :maintain_balances
      end
  end

  patch "merchants/ynab-mapping" => "merchants#update_ynab_mapping", as: :update_ynab_mapping_merchants
  patch "merchants/exclude_from_mapping" => "merchants#exclude_from_mapping", as: :exclude_from_merchants_mapping

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "main#index"
end

app/models/merchant.rb
class Merchant < ApplicationRecord
    has_one :merchant_category
    has_one :country
    has_one :ynab_payee

    def self.create_from_params(params)
        Merchant.find_or_create_by(name: params["name"]) do |merchant|
            merchant.name = params["name"]
            merchant.city = params["city"]
            country_params = params["country"]
            country = Country.find_or_create_by(code: country_params["code"]) do |c|
                c.name = country_params["name"]
                c.alpha3 = country_params["alpha3"]
            end
            merchant.country_id = country.id
            merchant_category_params = params["category"]
            merchant_category = MerchantCategory.find_or_create_by(code: merchant_category_params["code"]) do |mc|
                mc.name = merchant_category_params["name"]
                mc.key = merchant_category_params["key"]
            end
            merchant.merchant_category_id = merchant_category.id
        end
    end
end

app/controllers/merchants_controller.rb
# frozen_string_literal: true

class MerchantsController < ApplicationController
    def show
        @merchant = Merchant.find_by(id: params[:id])
    end

    def index
        unless user_signed_in?
            redirect_to new_session_path
            return
        end
        @merchants = Merchant.where("ynab_payee_id is null and exclude_from_ynab_mapping = false").sort_by(&:name)
        @ynab_payees = YnabPayee.all.sort_by(&:name)
    end

    def exclude_from_mapping
        unless user_signed_in?
            redirect_to new_session_path
            return
        end
        merchant = Merchant.find_by(id: params[:merchant_id])
        merchant.update(exclude_from_ynab_mapping: true)
        redirect_to merchant_path(merchant)
    end

    def update_ynab_mapping
        unless user_signed_in?
            redirect_to new_session_path
            return
        end
        merchant = Merchant.find_by(id: params[:merchant_id])
        merchant.update(ynab_payee_id: params[:payee])
        redirect_to merchant_path(merchant)
    end
end

app/views/merchants/index.html.erb
<%= turbo_frame_tag "merchants" do %>
    <div class="flex-col" data-controller="merchant">
        <h1 class="text-xl mb-5">Map Merchants</h1>
        <div class="grid grid-cols-1 lg:grid-cols-4 gap-6">
            <% @merchants.each do |merchant| %>
                <%= turbo_frame_tag dom_id(merchant) do %>
                    <div class="flex flex-col p-10 bg-white rounded-xl border border-neutral-800">
                        <%= form_with url: update_ynab_mapping_merchants_path, method: :patch do |form| %>
                            <h2 class="font-bold text-xl mb-6"><%= merchant.name %></h2>
                            <%= form.hidden_field :merchant_id, value: merchant.id %>
                            <%= form.select :payee,
                                            @ynab_payees.map { |payee| [payee.name, payee.id] },
                                            {
                                                include_blank: "Choose payee"
                                            },
                                            {
                                                data: {
                                                    merchant_target: "payeeSelect"
                                                },
                                                class: "mb-6"
                                            }
                            %>
                            <!--                            <div class="my-4">-->
                            <%#= form.check_box :exclude %>
                            <%#= form.label :exclude, "Exclude" %>
                            <!--                            </div>-->

                            <div>
                                <%= form.submit "UPDATE",
                                                data: { turbo_submits_with: "Updating..." },
                                                class: "px-6 py-1 font-mono rounded-full bg-neutral-200 border border-neutral-800 hover:bg-neutral-800 hover:text-neutral-300 cursor-pointer" %>
                            </div>
                        <% end %>
                        <%= button_to "EXCLUDE",
                                      exclude_from_merchants_mapping_path,
                                      method: :patch,
                                      params: { merchant_id: merchant.id },
                                      class: "mt-4 px-6 py-1 font-mono rounded-full text-neutral-300 bg-neutral-800 border border-neutral-800 hover:bg-neutral-300 hover:text-neutral-800 cursor-pointer"
                        %>
                    </div>
                <% end %>
            <% end %>
        </div>

    </div>
<% end %>

app/views/merchants/show.html.erb
<%= turbo_frame_tag dom_id(@merchant) do %>
    <h1><%= @merchant.name %></h1>
    <p>Status: <%= @merchant.ynab_payee_id.nil? ? "Unmapped" : "Mapped" %></p>
<% end %>